### ISSUE TITLE
nz-input cannot be disabled if ngModel is missing

### ISSUE THREAD

**Issue by krokofant** [NG-ZORRO/ng-zorro-antd#4655]
## Version
8.5.2

## Environment
all

## Description
https://stackblitz.com/edit/angular-v3twsq?file=src/app/app.component.ts

Without an ngModel the nz-input cannot be disabled properly. You can still select it and write text. See the the first input in the link above.

**Comment by vthinkxie** [comment]
Hi, this issue has been fixed by angular v9, we will release ng-zorro-antd v9 soon.

**Comment by Even-Lau** [comment]
It seems that this issue still existed in `"ng-zorro-antd": "^12.1.0",`. I highly dout that you guys had solved the problem.

**Comment by JasonAtallah** [comment]
Seems to still be an issue in `^13.2.1`

**Comment by donkee** [comment]
Still an issue in `^13.3.2` too

**Comment by shadmanontheoffice** [comment]
Still an issue in ^13.1.1
