### ISSUE TITLE
form.disable() for Reactive Form (v9) only partially applies disable style to input group

### ISSUE THREAD

**Issue by christarnowski** [NG-ZORRO/ng-zorro-antd#5137]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-9-reactive-form-disabled-input-issue](https://stackblitz.com/edit/ng-zorro-antd-9-reactive-form-disabled-input-issue)

### Steps to reproduce
1. Create a Reactive Form using API available in Angular 9.
2. Use NG-ZORRO's input component with icon prefix (via `nz-input-group`).
3. Call FormGroup's `form.disable()`.

### What is expected?
The whole `nz-input-group` styled as disabled.

### What is actually happening?
Only raw input text input area gets disabled style.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.0.2 |
| Browser | Firefox Developer Edition 76.0b8 (64-bit) |

**Comment by vthinkxie** [comment]
fixed by #5082

**Comment by majakovacevic** [comment]
This issue still seems present in v9.1.2. Here is the same reproducible app in v9.1.2: https://stackblitz.com/edit/ng-zorro-antd-9-reactive-form-disabled-input-issue-duhe6n

And here is the same issue presented in more complex scenario that we are experiencing after migration to v9:
v9.1.1: https://stackblitz.com/edit/ng-zorro-antd-9-reactive-form-disabled-input-issue-swxhev
v8.5.1 (issue not present): https://stackblitz.com/edit/angular-puqhtc
