### ISSUE TITLE
NzModalModule(nzDraggable): dragging a modal that contains an open nz-select doesn't move the nz-select with the modal

### ISSUE THREAD

**Issue by mfatha-wm** [NG-ZORRO/ng-zorro-antd#8844]
[Screencast from 21-10-2024 18:35:47.webm](https://github.com/user-attachments/assets/9f17efef-6e47-4739-9088-7f39709f01a1)
### Reproduction link
[https://stackblitz.com/edit/angular-bddtcp-lxglnw?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-bddtcp-lxglnw?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Open a draggable modal, open a select inside the modal, drag the modal. 

### What is expected?
The select either closes or moves with the modal. 

### What is actually happening?
The select stays still. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.1 |
| Browser | Chrome |

**Comment by ParsaArvanehPA** [comment]
Hi @mfatha-wm m
Thank you for reporting this issue,
This issue has been fixed in #8804.

**Comment by zhurongwell** [comment]
@ParsaArvanehPA 
> Hi [@mfatha-wm](https://github.com/mfatha-wm) Thank you for reporting this issue, This issue has been fixed in [#8804](https://github.com/NG-ZORRO/ng-zorro-antd/pull/8804).

I found that the issue still exists when using the latest version.

**Comment by piggylux** [comment]
I updated the stackblitz with the latest ng-zorro version to show the issue is still there

https://stackblitz.com/edit/aexqa9p1?file=src%2Fapp%2Fapp.component.ts
